Numpy Assignment

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [105]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

In [106]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [107]:
type(list_)

list

In [108]:
type(array_list)

numpy.ndarray

yes variable_list and array_list are both doffernt data structure but in array_list is more specialized operation in numpy data structure.

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [109]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

In [110]:
for i in list_:
    print(type(i))
    
for j in array_list:  
    print(type(j))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

In [111]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_, dtype = int)

In [112]:
array_list

array([1, 2, 3, 4, 5])

In [113]:
for i in list_:
    print(type(i))
    
for j in array_list:  
    print(type(j))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


yes there be any difference in the data type of the elements present in both the variables, list_ and
arra_list because in array_list datatype should be int while in list_ variable it should be str

In [114]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [115]:
np.shape(num_array)

(2, 3)

In [116]:
np.size(num_array)

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]


In [117]:
import numpy.matlib as nm

nm.zeros((3,3))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [118]:
import numpy.matlib as nm

nm.eye(5,5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])